name: "Release"
on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  next-version:
    name: Get next release version
    runs-on: ubuntu-latest
    outputs:
      last-release-version: ${{ steps.last-release.outputs.release }}
      new-release-version: ${{ format('v{0}', steps.next-release.outputs.new-release-version) }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: find current latest release version
        uses: pozetroninc/github-action-get-latest-release@master
        id: last-release
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.CUSTOM_GITHUB_PERSONAL_TOKEN }}

      - name: find next release version
        id: next-release
        run: npm_config_yes=true npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_PERSONAL_TOKEN }}

      - name: print outputs
        run: |
          echo "Last release version = ${{ steps.last-release.outputs.release }}"
          echo "Next release version = ${{ steps.next-release.outputs.new-release-version }}"

  release:
    name: Cut a release on GitHub
    runs-on: ubuntu-latest
    needs: next-version
    if: needs.next-version.outputs.new-release-version != needs.next-version.outputs.last-release-version
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: make a release on GitHub
        run: npm_config_yes=true npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_PERSONAL_TOKEN }}
          GIT_AUTHOR_NAME: 'GP'
          GIT_COMMITTER_NAME: 'GP'
          GIT_AUTHOR_EMAIL: 'me@httgp.com'
          GIT_COMMITTER_EMAIL: 'me@httgp.com'
